### ISSUE TITLE
Started container on Linux Mint 19 x64 and no internet access

### ISSUE THREAD

**Issue by seth100** [gordyf/dnscrypt-proxy-2-docker#2]
Hi,

I have created the container on my Linux Mint 19 x64.
Then I have:

- stopped `systemd-resolved`: `sudo systemctl stop systemd-resolved`, listening on port `53`;
- put my machine IP as DNS server resolver in Network Manager: `192.168.1.5` (also tried with the docker container IP `172...`)
- started the container (about `dnscrypt-proxy` I have used my custom `dnscrypt-proxy.toml` file where I've just edited `server_names` and changed from `ipv6_servers = true` to `ipv6_servers = false`.

Any help with that?
Maybe it would be useful a short guide to explain how to use the container as main host resolver on e.g. Ubuntu 18.04 or Linux Mint 19!?

Thanks a lot!

**Comment by gordyf** [comment]
Hmm, what you're describing sounds like it should work. If you run `dig google.com @192.168.1.5` on your Linux machine while the container is running, do you get a response? Can you provide the `docker run ...` or `docker-compose.yml` you're using to start the container?

**Comment by seth100** [comment]
@gordyf thank you.
I found the issue, I also had to edit `/etc/resolv.conf` file, setting `nameserver 127.0.0.1`.
Anyway, the command `dig google.com @192.168.1.5` was working even without that change.
Thanks
